name: naturemedix
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.2
  connectivity_plus: ^6.0.5
  file_picker: ^8.1.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.1
  flutter_login_facebook: ^2.0.1
  flutter_slidable: ^3.1.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  rounded_loading_button: ^2.1.0
  shared_preferences: ^2.3.2
  slide_to_act: ^2.0.2
  twitter_login: ^4.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/
    - assets/herbal/plant/
    - assets/herbal/remedy/
